### ISSUE TITLE
Incorrect output from biomarker_extraction.gene_protein_chemical()

### ISSUE THREAD

**Issue by rkatriel** [Damonlin11/FDA-Target-Therapy-Label-Extraction#6]
Hi,

In the example you provide, the drug (chemical) 'TECENTRIQ' is incorrectly labeled as a 'protein':

```
# Extract gene, protein, and drug labels from a string:
>>> txt = "Patients with EGFR or ALK genomic tumor aberrations should have disease progression on FDA-approved therapy for NSCLC harboring these aberrations prior to receiving TECENTRIQ."
>>> biomarker_extraction.gene_protein_chemical(text = txt, gene= 1, protein = 1, chemical = 1)
{'gene': ['EGFR', 'ALK genomic'], 'protein': ['EGFR', 'TECENTRIQ'], 'chemical': []}
```

Strangely, in the latest version 'NSCLC' is (incorrectly) recognized as a 'protein' (it's a disease) and 'TECENTRIQ' is not recognized at all:

`{'gene': ['ALK genomic'], 'protein': ['EGFR', 'NSCLC'], 'chemical': []}
`

Can you please look into this?

Thanks,
Ron

**Comment by Damonlin11** [comment]
Hi Ron, 

Thank you for your comments.

The prediction of proteins is based on the model en_ner_jnlpba_md (A spaCy NER model trained on the JNLPBA corpus). The prediction on chemicals is based on the model en_ner_bionlp13cg_md (A spaCy NER model trained on the BIONLP13CG corpus). I double-checked the function and verified that the model en_ner_jnlpba_md predicts that TECENTRIQ is a protein, though I understand that TECENTRIQ is meant as a chemical based on the context of the example sentence. 

Regarding the output you provided, could you provide more information on how you got it? Which package/model did you mean for the "latest version" you mentioned? If possible, could you provide a piece of code that generated the output? 

Thanks, 
Junxia

**Comment by rkatriel** [comment]
Hi Junxia,

I downloaded biomarker_nlp using pip as described on your GitHub page (https://pypi.org/project/biomarker-nlp/). The models were downloaded using

pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_ner_jnlpba_md-0.5.1.tar.gz
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_ner_bionlp13cg_md-0.5.1.tar.gz

I ran your sample code from GitHub (without any changes - except adding print statements) in PyCharm. Please see the attached Python script below.

Thanks,
Ron

--

**Comment by Damonlin11** [comment]
Hi Ron, 

I didn't see there is an attached Python script in your response. 

I got the same output as yours if I used the latest version (v0.5.1) of the Scispacy NER pre-training models. I further checked the direct output from the models (please see the code below) and confirmed that the output from gene_protein_chemical() aligns with the output from Scispacy NER pre-training models while using the latest version (v0.5.1). It is so surprising that the results from the latest version changed a lot. It may be due to the change of the entity tagging in the training corpus or the training algorithms in the latest version of the models. If you want to get more up-to-date information about the models, please see the link at the very bottom.

## Install and load Scispacy NER pre-training models
pip install biomarker_nlp
pip install scispacy
pip install -U spacy
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_ner_craft_md-0.5.1.tar.gz
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_ner_jnlpba_md-0.5.1.tar.gz

import en_ner_craft_md
import en_ner_jnlpba_md
nlp_craft = en_ner_craft_md.load()
nlp_jnlpha = en_ner_jnlpba_md.load()
txt = "Patients with EGFR or ALK genomic tumor aberrations should have disease progression on FDA-approved therapy for NSCLC harboring these aberrations prior to receiving TECENTRIQ."

## Detect gene
doc = nlp_craft(txt)
geneList = []
for entity in doc.ents:
**if entity.label_=='GGP':
****geneList.append(entity.text)
print(geneList)
Output: ['ALK genomic']

## Detect protein
doc = nlp_jnlpha(txt)
proteinList = []
for entity in doc.ents:
**if entity.label_=='PROTEIN':
****proteinList.append(entity.text)
print(proteinList)
Output: ['EGFR', 'NSCLC']

You can also detect other types of entities by changing the entity's label in the code above. Please see this link for more information: https://allenai.github.io/scispacy/

Please let me know if you have more questions. 

Best Regards, 
Junxia

**Comment by rkatriel** [comment]
Hi Junxia,

Thanks for sharing that. Just one comment: NSCLC is not a protein - it stands for Non-Small Cell Lung Cancer. This is probably a good example where the statistical nature of the model fails and additional validation (e.g., against an authoritative database) would really help.

Best,
Ron

**Comment by Damonlin11** [comment]
Hi Ron, 

I agree with you. Some of the predicted results don't make sense. I may look into what have been changed in the latest version of models in the Scispacy package later on. Thank you very much for raising this issue. 

Best Regards, 
Junxia
